Import("env")

env.Append(
    SDK_HEADERS=[
        File("../../icons/assets_icons.h"),
        File("momentum.h"),
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
)

libenv = env.Clone(FW_LIB_NAME="momentum")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")
libenv.Depends(sources, env["MOMENTUM_ZH_FONT_GEN"])

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
